-- MySQL Script generated by MySQL Workbench
-- 02/27/16 15:57:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mybase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mybase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mybase` ;
USE `mybase` ;

-- -----------------------------------------------------
-- Table `mybase`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybase`.`Customer` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybase`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybase`.`Company` (
  `companyID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `VAT` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `Companycol` VARCHAR(45) NULL,
  PRIMARY KEY (`companyID`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mybase`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybase`.`Product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `productnumber` INT NULL,
  `warranty` INT NULL,
  `price` DOUBLE NULL,
  `number` INT NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybase`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybase`.`Bill` (
  `billID` INT NOT NULL AUTO_INCREMENT,
  `orderDate` DATETIME NULL,
  `orderTime` TIME NULL,
  `Customer_customerID` INT NOT NULL,
  `Company_companyID` INT NOT NULL,
  PRIMARY KEY (`billID`, `Customer_customerID`, `Company_companyID`),
  INDEX `fk_Bill_Customer_idx` (`Customer_customerID` ASC),
  INDEX `fk_Bill_Company1_idx` (`Company_companyID` ASC),
  CONSTRAINT `fk_Bill_Customer`
    FOREIGN KEY (`Customer_customerID`)
    REFERENCES `mybase`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bill_Company1`
    FOREIGN KEY (`Company_companyID`)
    REFERENCES `mybase`.`Company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mybase`.`Product_has_Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mybase`.`Product_has_Bill` (
  `Product_productID` INT NOT NULL,
  `Bill_billID` INT NOT NULL,
  `Bill_Customer_customerID` INT NOT NULL,
  `Bill_Company_companyID` INT NOT NULL,
  PRIMARY KEY (`Product_productID`, `Bill_billID`, `Bill_Customer_customerID`, `Bill_Company_companyID`),
  INDEX `fk_Product_has_Bill_Bill1_idx` (`Bill_billID` ASC, `Bill_Customer_customerID` ASC, `Bill_Company_companyID` ASC),
  INDEX `fk_Product_has_Bill_Product1_idx` (`Product_productID` ASC),
  CONSTRAINT `fk_Product_has_Bill_Product1`
    FOREIGN KEY (`Product_productID`)
    REFERENCES `mybase`.`Product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Bill_Bill1`
    FOREIGN KEY (`Bill_billID` , `Bill_Customer_customerID` , `Bill_Company_companyID`)
    REFERENCES `mybase`.`Bill` (`billID` , `Customer_customerID` , `Company_companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
